name: Kaggle Dataset Downloader

on:
  push:
    branches:
      - main

jobs:
  download-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install kaggle pandas

      - name: Download Dataset
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          python -c "
from script import download_kaggle_dataset, load_kaggle_csv
download_kaggle_dataset('arshkon/linkedin-job-postings', download_path='datasets')
data = load_kaggle_csv('datasets', 'linkedin_jobs.csv')
print(data.head())"
